services:
  web:
    type: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

cron:
  - name: "Uptime Monitoring"
    schedule: "every 10 minutes"
    url: https://hotmail-api-inbox.onrender.com/health